### ISSUE TITLE
Avoid use of emoji in command names

### ISSUE THREAD

**Issue by Tyriar** [githubnext/spectrum#1]
Hi from the VS Code core team. I noticed you use an emoji in your command name which doesn't follow our extension guidelines:

https://code.visualstudio.com/api/references/extension-guidelines#command-palette

![image](https://user-images.githubusercontent.com/2193314/152399966-d25a440a-9778-45af-8bb9-6e34488fcaa8.png)

**Comment by mattrothenberg** [comment]
Published! To clarify, is it OK to have an emoji as the `title` of the webview?

![Screen Shot 2022-02-07 at 11 20 47 AM](https://user-images.githubusercontent.com/5148596/152828352-27ed1142-1003-4436-add3-d6ca29d459c9.png)

**Comment by Tyriar** [comment]
@mattrothenberg I don't think there's a problem with that. The issue was when looking at the command palette, the spectrum command stuck out like a sore thumb 🙂
